import { CIRCUIT } from "./weekend.ts";
import { DEFAULT_LOCALE, type L, type Locale } from "./i18n.ts";

/**
 * A transparent tyre and pit-stop model for Sepang.
 *
 * Every constant is in the open so it can be argued with. None of it is
 * simulated precision: it is a small physical model tuned to the things Sepang
 * is actually known for — track temperatures past 50 °C, hard tyre wear, and a
 * race that historically needed two stops when most tracks needed one.
 *
 * The model owns every number the app ever states about strategy. Nothing here
 * is generated by a language model, and nothing here comes from live timing —
 * no lawful public source for that exists.
 */

export const COMPOUNDS = ["soft", "medium", "hard"] as const;
export type Compound = (typeof COMPOUNDS)[number];

/** Reference dry race lap, low fuel, fresh medium, 45 °C track. Seconds. */
export const BASE_LAP_S = 96.0;

/** Sepang's pit lane costs roughly this much against staying out. Seconds. */
export const PIT_LOSS_S = 22.0;

/** Fuel burn-off: the car gets this much quicker per lap completed. */
export const FUEL_GAIN_S_PER_LAP = 0.035;

/** Track temperature the degradation rates below are quoted at. */
export const REFERENCE_TRACK_C = 45;

/** Each degree above the reference adds this fraction to the wear rate. */
export const TEMP_SENSITIVITY = 0.035;

/** Past its useful life a tyre falls off a cliff rather than fading linearly. */
export const CLIFF_MULTIPLIER = 3;

/** Compound names live here, with the numbers they belong to, not in the UI copy. */
export const TYRES: Record<
  Compound,
  { label: L; offsetS: number; degSPerLap: number; lifeLaps: number; colour: string }
> = {
  // Quicker when new, gone soonest. Life figures are at the reference temperature.
  soft: {
    label: { en: "Soft", zh: "软胎" },
    offsetS: -0.8,
    degSPerLap: 0.13,
    lifeLaps: 18,
    colour: "#e8483f",
  },
  medium: {
    label: { en: "Medium", zh: "中性胎" },
    offsetS: 0.0,
    degSPerLap: 0.08,
    lifeLaps: 28,
    colour: "#ffc61e",
  },
  hard: {
    label: { en: "Hard", zh: "硬胎" },
    offsetS: 0.7,
    degSPerLap: 0.05,
    lifeLaps: 40,
    colour: "#e6ebf2",
  },
};

/** Formula 1 requires two different dry compounds in a dry race. */
export const MIN_COMPOUNDS = 2;

export const RACE_LAPS = CIRCUIT.laps;

/** How much faster wear runs than at the reference temperature. Never negative. */
export function tempFactor(trackC: number): number {
  return Math.max(0.3, 1 + (trackC - REFERENCE_TRACK_C) * TEMP_SENSITIVITY);
}

/**
 * Time lost on one lap to tyre wear, for a tyre that has already done `age` laps.
 * Linear while the tyre is alive, then steep once it is past its life.
 */
export function degradationS(compound: Compound, age: number, trackC: number): number {
  const t = TYRES[compound];
  const rate = t.degSPerLap * tempFactor(trackC);
  const life = t.lifeLaps / tempFactor(trackC);
  return age <= life ? rate * age : rate * life + rate * CLIFF_MULTIPLIER * (age - life);
}

/** Lap time on `lap` (1-indexed) with a tyre `age` laps old. */
export function lapTimeS(lap: number, compound: Compound, age: number, trackC: number): number {
  const fuel = (RACE_LAPS - lap) * FUEL_GAIN_S_PER_LAP;
  return BASE_LAP_S + fuel + TYRES[compound].offsetS + degradationS(compound, age, trackC);
}

export type Stint = { compound: Compound; startLap: number; laps: number };
export type Plan = {
  stints: Stint[];
  stops: number;
  /** Laps on which the car pits, i.e. the start lap of each stint after the first. */
  stopLaps: number[];
  totalS: number;
};

/**
 * The quickest way to get through the race, found by search rather than by
 * assertion.
 *
 * Stint costs are prefix-summed first, so evaluating any stint is O(1); the
 * search is then a small dynamic program over (lap, stops used, compounds used).
 * Brute-forcing three-stop plans instead would be about two million
 * combinations, which is too slow to sit behind a slider.
 */
export function bestPlans(trackC: number, maxStops = 3, top = 3): Plan[] {
  // cost[c][start][len] via prefix sums of lap times for a stint started at `start`.
  const stintCost: Record<Compound, number[][]> = {
    soft: [],
    medium: [],
    hard: [],
  };
  for (const c of COMPOUNDS) {
    for (let start = 0; start < RACE_LAPS; start++) {
      const row: number[] = [0];
      let acc = 0;
      for (let len = 1; start + len <= RACE_LAPS; len++) {
        acc += lapTimeS(start + len, c, len - 1, trackC);
        row.push(acc);
      }
      stintCost[c][start] = row;
    }
  }

  const bit = (c: Compound) => 1 << COMPOUNDS.indexOf(c);
  const popcount = (m: number) => (m & 1) + ((m >> 1) & 1) + ((m >> 2) & 1);

  type Node = { time: number; from: [number, number, number] | null; stint: Stint | null };
  // best[lap][stops][mask]
  const best: Node[][][] = Array.from({ length: RACE_LAPS + 1 }, () =>
    Array.from({ length: maxStops + 1 }, () =>
      Array.from({ length: 8 }, () => ({ time: Infinity, from: null, stint: null }) as Node),
    ),
  );
  best[0][0][0] = { time: 0, from: null, stint: null };

  for (let lap = 0; lap < RACE_LAPS; lap++) {
    for (let stops = 0; stops <= maxStops; stops++) {
      for (let mask = 0; mask < 8; mask++) {
        const here = best[lap][stops][mask];
        if (!isFinite(here.time)) continue;
        const nextStops = lap === 0 ? stops : stops + 1;
        if (nextStops > maxStops) continue;

        for (const c of COMPOUNDS) {
          const row = stintCost[c][lap];
          for (let len = 1; lap + len <= RACE_LAPS; len++) {
            const t = here.time + row[len] + (lap === 0 ? 0 : PIT_LOSS_S);
            const nMask = mask | bit(c);
            const cell = best[lap + len][nextStops][nMask];
            if (t < cell.time) {
              cell.time = t;
              cell.from = [lap, stops, mask];
              cell.stint = { compound: c, startLap: lap + 1, laps: len };
            }
          }
        }
      }
    }
  }

  const finished: Plan[] = [];
  for (let stops = 1; stops <= maxStops; stops++) {
    for (let mask = 0; mask < 8; mask++) {
      if (popcount(mask) < MIN_COMPOUNDS) continue;
      const cell = best[RACE_LAPS][stops][mask];
      if (!isFinite(cell.time)) continue;

      const stints: Stint[] = [];
      let lap: number = RACE_LAPS;
      let s = stops;
      let m = mask;
      while (best[lap][s][m].stint) {
        const node = best[lap][s][m];
        stints.unshift(node.stint!);
        [lap, s, m] = node.from!;
      }
      finished.push({
        stints,
        stops,
        stopLaps: stints.slice(1).map((x) => x.startLap - 1),
        totalS: cell.time,
      });
    }
  }

  // One entry per distinct plan shape, quickest first.
  const seen = new Set<string>();
  return finished
    .sort((a, b) => a.totalS - b.totalS)
    .filter((p) => {
      const key = p.stints.map((s) => `${s.compound}${s.laps}`).join("-");
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .slice(0, top);
}

/** mm:ss.s, the way a race time is normally written. */
export function formatRaceTime(totalS: number): string {
  const h = Math.floor(totalS / 3600);
  const m = Math.floor((totalS % 3600) / 60);
  const s = totalS % 60;
  return `${h}:${String(m).padStart(2, "0")}:${s.toFixed(1).padStart(4, "0")}`;
}

export function formatDelta(deltaS: number): string {
  return `${deltaS >= 0 ? "+" : ""}${deltaS.toFixed(1)}s`;
}

/**
 * "13, 30 and 43" rather than "13 and 30 and 43" — and never an English "and"
 * inside a Chinese sentence, which is what a locale-blind join produces.
 */
export function formatLapList(laps: number[], locale: Locale = DEFAULT_LOCALE): string {
  if (laps.length === 0) return "";
  if (laps.length === 1) return String(laps[0]);
  if (locale === "zh") return laps.join("、");
  return `${laps.slice(0, -1).join(", ")} and ${laps[laps.length - 1]}`;
}
